
const projects = [
  {
    id: 1,
    name: "PiperNet",
    link: "https://github.com/Win4esterD/PiperNet_landing_page",
    technologies: "HTML, CSS, Git",
    publishment: "https://piper-net-landing-page.vercel.app/",
  },
  {
    id: 2,
    name: "Travel LP",
    link: "https://github.com/Win4esterD/travel",
    technologies: "HTML, CSS, JavaScript, Git",
    publishment: "https://travel-ten-rust.vercel.app/",
  },
  {
    id: 3,
    name: "URL_Shortner",
    link: "https://github.com/Win4esterD/URL_Shortner",
    technologies: "Python, Django, HTML, CSS, Git",
    publishment: "http://win4esterd.pythonanywhere.com/",
  },
  {
    id: 4,
    name: "Online Zoo",
    link: "https://github.com/Win4esterD/online-zoo",
    technologies: "HTML, CSS, JavaScript, Git",
    publishment: "https://online-zoo-hvy8-d8a4t2c4l-win4esterd.vercel.app/",
  },
  {
    id: 5,
    name: "Quince game",
    link: "https://github.com/Win4esterD/gem-puzzle",
    technologies: "CSS, JavaScript, Git",
    publishment: "https://gem-puzzle-sepia.vercel.app/index.html",
  },
  {
    id: 6,
    name: "SongBird",
    link: "https://github.com/Win4esterD/SongBird/",
    technologies: "HTML, CSS, JavaScript, Git",
    publishment: "https://song-bird-win4esterd.vercel.app/",
  },
  {
    id: 7,
    name: "EA test task",
    link: "https://github.com/Win4esterD/Test-Front-end-EA/tree/develop",
    technologies: "React, SaSS, Webpack, JavaScript, Git",
    publishment: "https://test-front-end-ea.vercel.app/",
  },
  {
    id: 8,
    name: "Random Avatars Generator",
    link: "https://github.com/Win4esterD/RandomAvatarGenerator",
    technologies: "React, NextJS, JavaScript, CSS, Git",
    publishment: "https://random-avatar-generator-beta.vercel.app/",
  },
  {
    id: 9,
    name: "Tarot Divination",
    link: "https://github.com/Win4esterD/Divination",
    technologies: "Next.js, React, SaSS, Webpack, JavaScript, Git",
    publishment: "https://divination-two.vercel.app/",
  },
  {
    id: 10,
    name: "Library",
    link: "https://github.com/Win4esterD/Library",
    technologies: "React, SaSS, JavaScript, Git",
    publishment: "https://library-lake-xi.vercel.app/",
  },
  {
    id: 11,
    name: "Task Manager",
    link: "https://github.com/Win4esterD/Task-Manager/",
    technologies: "React, JavaScript, CSS, Git",
    publishment: "https://task-manager-2p7rlv5wp-win4esterd.vercel.app/",
  },
  {
    id: 12,
    name: "Nasa, picture of the day",
    link: "https://github.com/Win4esterD/NASA",
    technologies: "React, Next.js, Material UI, Git",
    publishment: "https://nasa-ten-xi.vercel.app/",
  },
];
